apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-springboot-first-app
  labels:
    app: demo-springboot-first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-springboot-first-app
  template:
    metadata:
      labels:
        app: demo-springboot-first-app
    spec:
      containers:
      - name: demo-springboot-first-app
        image: sanjeevjha77/cicd-demo-sanjeev:1
        ports:
        - containerPort: 8080
